### ISSUE TITLE
Package missing software

### ISSUE THREAD

**Issue by BobyMCbobs** [flathub/com.github.bvschaik.julius#2]
Julius fails to launch. I'm getting the following errors when I try to launch it:
```
INFO: Julius version 1.3.1
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from base path /app/bin/
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.

missing software! (we will try basic console input)

 ___________
/           \ 
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript
or kdialog
or zenity (or matedialog or qarma)
or python (2 or 3)
 + tkinter + python-dbus (optional)
or dialog (opens console if needed)
or xterm + bash
   (opens console for basic input)
or existing console for basic input

press enter to continue 



Julius requires the original files from Caesar 3 to run.

Please select your Caesar 3 folder.

Select folder
(esc+enter to cancel): 
^[

INFO: Exiting: game pre-init failed
```

**Comment by bvschaik** [comment]
This is actually working as intended: the library I'm using to let the user select a Caesar 3 directory (TinyFileDialogs) leverages existing system resources to show the dialog, so Julius doesn't need to include for example all of KDE to just get a dialog. If no suitable programs are found, you get this command-line selector. Perhaps I should remove the warning though.

Out of curiosity: what kind of desktop environment are you running?

**Comment by BobyMCbobs** [comment]
> This is actually working as intended: the library I'm using to let the user select a Caesar 3 directory (TinyFileDialogs) leverages existing system resources to show the dialog, so Julius doesn't need to include for example all of KDE to just get a dialog. If no suitable programs are found, you get this command-line selector. Perhaps I should remove the warning though.
> 
> Out of curiosity: what kind of desktop environment are you running?

I'm using GNOME 3.34.
I'd think that the app shouldn't depend on any system packages since it's a Flatpak, may I suggest packaging something like `zenity` into the package - that way there aren't anymore system dependencies (hopefully).

**Comment by bvschaik** [comment]
Now I'm thinking, since it's Flatpak, _can_ it actually access system resources since it's sandboxed? With Gnome installed I would expect zenity to be available on the host.

To be honest, I'm not familiar with Flatpak at all - someone else packaged Julius and told me how to do new releases. So if anyone could help me add zenity as dependency, I'd be grateful.

**Comment by barthalion** [comment]
I'm pretty sure it worked when I wrote the manifest. No idea what happened, I will have a look in the evening.

**Comment by barthalion** [comment]
@bvschaik Zenity is available in the runtime:

```
❯ flatpak run --command=zenity com.github.bvschaik.julius --version
3.32.0
```

**Comment by bvschaik** [comment]
@barthalion Apparently TinyFileDialogs doesn't think it's available. It tries to do a `which zenity`, perhaps that doesn't "see" the zenity executable?

**Comment by barthalion** [comment]
It seems to detect it:

**Comment by barthalion** [comment]
It does seem to be detected:

```
114   stat("/var/home/bpiotrowski/.local/bin/zenity", 0x7ffe74ff7860) = -1 ENOENT (No such file or directory)
114   stat("/var/home/bpiotrowski/bin/zenity", 0x7ffe74ff7860) = -1 ENOENT (No such file or directory)
114   stat("/app/bin/zenity", 0x7ffe74ff7860) = -1 ENOENT (No such file or directory)
114   stat("/usr/bin/zenity", {st_mode=S_IFREG|0755, st_size=127504, ...}) = 0
114   stat("/usr/bin/zenity", {st_mode=S_IFREG|0755, st_size=127504, ...}) = 0
114   geteuid()                         = 1000
114   getegid()                         = 1000
114   getuid()                          = 1000
114   getgid()                          = 1000
114   access("/usr/bin/zenity", X_OK)   = 0
114   stat("/usr/bin/zenity", {st_mode=S_IFREG|0755, st_size=127504, ...}) = 0
114   geteuid()                         = 1000
114   getegid()                         = 1000
114   getuid()                          = 1000
114   getgid()                          = 1000
114   access("/usr/bin/zenity", R_OK)   = 0
114   fstat(1<pipe:[2305353]>, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
114   write(1<pipe:[2305353]>, "/usr/bin/zenity\n", 16) = 16
```

I need to dive into TinyFileDialogs source code to see what's going on.

**Comment by bvschaik** [comment]
The source code is here: https://github.com/bvschaik/julius/blob/master/ext/tinyfiledialogs/tinyfiledialogs.c

**Comment by barthalion** [comment]
@BobyMCbobs Can you try running `flatpak run --nosocket=wayland com.github.bvschaik.julius`?

Looks like the problem here is that TinyFileDialogs tries to run xprop (to ensure directory chooser dialog is the active window) and that just doesn't work for native Wayland windows.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs Can you try running `flatpak run --nosocket=wayland com.github.bvschaik.julius`?
> 
> Looks like the problem here is that TinyFileDialogs tries to run xprop (to ensure directory chooser dialog is the active window) and that just doesn't work for native Wayland windows.

Running this opens a GTK-styled dialog. Woohoo!

**Comment by barthalion** [comment]
@bvschaik So we can either drop Wayland support or xprop usage from TinyFileDialogs.

**Comment by BobyMCbobs** [comment]
If possible, please keep Wayland support as it's a newer technology and will supersede Xorg

**Comment by bvschaik** [comment]
@barthalion Thanks for looking into it. I'd say drop xprop usage from TinyFileDialogs then. However, it's not clear to me why it's actually needed, and the [commit logs](https://sourceforge.net/p/tinyfiledialogs/code/ci/1c1b70de5a1991d4fa814026a368ba53e16154e5/log/?path=/tinyfiledialogs.c) for TinyFileDialogs just list a version number so that's not helpful at all.

**Comment by bvschaik** [comment]
I've looked into it. It seems xprop is only used to make the folder select dialog have the active window as "parent". But since Julius is showing this dialog before creating its own window, it will be attached to the application that opened Julius instead. In other words: for us, xprop is not necessary at all.

But, looking through the TinyFileDialogs code, I don't understand how xprop can be the cause. Xprop is only used when actually showing the dialog, not for detecting whether for example zenity is present.

I've just set up a virtual machine with Debian + Gnome + Wayland, I've been able to reproduce this issue. I'm going to debug it.

**Comment by bvschaik** [comment]
I found the cause: somehow the `$DISPLAY` environment variable is not set within the Flatpak environment. I just disabled the check for graphics mode -- Julius will not run without a display anyway. Next release this will work properly.

**Comment by vareille** [comment]
Hi, I am the author of tinyfiledialogs. In version 3.7.2, I've taken this into account. I took care of the xprop issue and I've added a flag to tell tinyfiledialogs that a graphic display is present. Just set tinyfd_assumeGraphicDisplay = 1;

**Comment by bvschaik** [comment]
Thanks for letting us know, I'll have a look.
